---
title: "Data Wrangling Lecture"
output: github_document
---
  
## Data Import: CSV

Let's important data using the 'readr' package

```{r, echo = FALSE}
library(tidyverse)
```

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

```{r}
litters_df 
head(litters_df)
tail(litters_df)
```

```{r, eval = FALSE}
view(litters_df)
```

```{r}
skimr::skim(litters_df)
```

`read_csv` options...

```{r}
read_csv("data/FAS_litters.csv", na = c("", "NA", 999, 88), skip = 2)
```

## Other file formats
We need to read in a excel spreadsheet

```{r}
library(readxl)
```

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

```{r, eval = FALSE}
View(mlb_df)
```

```{r}
lotr_words_df = read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```

## Still more file formats...
Read in SAS Dataset

```{r}
library(haven)
```

```{r}
pulse_data = read_sas ("data/public_pulse_data.sas7bdat")
```

```{r, eval = FALSE}
View(pulse_data)
```

## Data Export

```{r}
write_csv(lotr_words_df, file = "data/lotr_words_df.csv")
```

```{r}
write_csv(lotr_words_df, file = "results/lotr_words_df.csv")
```


## Why not base R??
```{r}
dont_do_this_df = read.csv("data/FAS_litters.csv")
```